const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const {pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1050}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.resolve('index.html')).href);
 const initial=await page.evaluate(()=>({cash:STATE.totalCashBank,rev:STATE.monthlyRevenue,j:STATE.journals.length,orders:STATE.orders.length}));
 const output=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'coffee-pos-'));
 await page.getByRole('button',{name:'Pilih Aren Latte',exact:true}).click();
 await page.locator('#modSize').selectOption('large');
 await page.locator('#modSugar').selectOption('Less sugar');
 await page.locator('#modMilk').selectOption('oat');
 await page.locator('#modShot').selectOption('1');
 await page.locator('#modNote').fill('<img src=x onerror=alert(1)>');
 await page.screenshot({path:path.join(output,'modifier.png')});
 await page.getByRole('button',{name:'Simpan Item',exact:true}).click();
 await page.getByRole('button',{name:'Pilih Aren Latte',exact:true}).click();
 await page.getByRole('button',{name:'Simpan Item',exact:true}).click();
 assert.deepEqual(await page.evaluate(()=>STATE.posCart.map(i=>i.price)),[43000,26000]);
 assert.equal(await page.locator('#posCartList img').count(),0);
 await page.locator('#posCartList').getByRole('button',{name:'Edit racikan'}).first().click();
 await page.locator('#modQty').fill('2');
 await page.getByRole('button',{name:'Simpan Item',exact:true}).click();
 assert.equal(await page.evaluate(()=>STATE.posCart[0].qty),2);
 await page.locator('#posDiscountInput').fill('10000');
 await page.locator('#posDiscountInput').press('Tab');
 await page.getByRole('button',{name:'Simpan Tagihan',exact:true}).click();
 const id=await page.evaluate(()=>STATE.activeBills[0].id);
 assert.equal(await page.evaluate(()=>STATE.posCart.length),0);
 assert.equal(await page.evaluate(()=>STATE.orders.length),initial.orders);
 await page.getByRole('button',{name:/Tagihan Aktif/}).click();
 await page.screenshot({path:path.join(output,'active-bills.png')});
 await page.locator('#activeBillsList').getByRole('button',{name:'Buka',exact:true}).click();
 assert.equal(await page.evaluate(()=>STATE.posCart.length),2);
 assert.equal(await page.evaluate(()=>STATE.posDiscountAmount),10000);
 await page.getByRole('button',{name:'Kirim ke Dapur',exact:true}).click();
 await page.getByRole('button',{name:'Kirim ke Dapur',exact:true}).click();
 assert.equal(await page.evaluate(id=>STATE.orders.filter(o=>o.id===id).length,id),1);
 assert.equal(await page.evaluate(()=>STATE.totalCashBank),initial.cash);
 assert.equal(await page.evaluate(()=>STATE.journals.length),initial.j);
 await page.evaluate(id=>advanceOrderStatus(id,'selesai'),id);
 await page.getByRole('button',{name:'Pilih Butter Croissant',exact:true}).click();
 assert.equal(await page.locator('#modSize').isVisible(),false);
 await page.getByRole('button',{name:'Simpan Item',exact:true}).click();
 await page.getByRole('button',{name:'Kirim ke Dapur',exact:true}).click();
 assert.equal(await page.evaluate(id=>STATE.orders.find(o=>o.id===id).status,id),'proses');
 assert.equal(await page.evaluate(id=>STATE.orders.find(o=>o.id===id).items.length,id),3);
 await page.screenshot({path:path.join(output,'cashier.png')});
 const total=await page.evaluate(()=>posTotals());
 assert.equal(total.subtotal,137000); assert.equal(total.discount,10000); assert.equal(total.total,140970);
 await page.getByRole('button',{name:'Bayar Sekarang',exact:true}).click();
 await page.locator('#inputCashReceived').fill('1');
 await page.locator('#btnConfirmPay').click();
 assert.equal(await page.evaluate(()=>STATE.journals.length),initial.j);
 await page.locator('#inputCashReceived').fill(String(total.total));
 await page.locator('#btnConfirmPay').click();
 assert.equal(await page.evaluate(()=>STATE.totalCashBank),initial.cash+total.total);
 assert.equal(await page.evaluate(()=>STATE.monthlyRevenue),initial.rev+127000);
 assert.equal(await page.evaluate(()=>STATE.journals.length),initial.j+1);
 assert.equal(await page.evaluate(()=>STATE.activeBills.length),0);
 assert.equal(await page.evaluate(id=>STATE.orders.filter(o=>o.id===id).length,id),1);
 assert.equal(await page.evaluate(id=>STATE.orders.find(o=>o.id===id).paymentStatus,id),'paid');
 assert.match(await page.locator('#receiptPaper').innerText(),new RegExp(id));
 assert.match(await page.locator('#receiptPaper').innerText(),/Less sugar/);
 assert.equal(await page.locator('#receiptPaper img').count(),0);
 await page.evaluate(()=>executePayment());
 assert.equal(await page.evaluate(()=>STATE.journals.length),initial.j+1);
 await page.evaluate(()=>{closeModal('paymentModal');switchPosTab('pesanan')});
 await page.getByRole('button',{name:'Web Order',exact:true}).click();
 assert.equal(await page.locator('#orderCard-'+id).count(),0);
 await page.getByRole('button',{name:'Dine-in',exact:true}).click();
 assert.equal(await page.locator('#orderCard-'+id).count(),1);
 await page.getByRole('button',{name:'Delivery',exact:true}).click();
 assert.equal(await page.locator('.order-card').count(),0);
 await page.getByRole('button',{name:'Semua Pesanan',exact:true}).click();
 assert.equal(await page.locator('#orderCard-'+id).count(),1);
 // Switching bills preserves the current unsaved cart, and IDs never duplicate.
 await page.evaluate(()=>{switchPosTab('kasir');addProductToPosCart(MOCK_DATA.products[0]);holdCurrentCart();addProductToPosCart(MOCK_DATA.products[1])});
 const saved=await page.evaluate(()=>STATE.activeBills[0].id);
 await page.getByRole('button',{name:/Tagihan Aktif/}).click();
 await page.locator('#activeBillsList .bill-row').first().getByRole('button',{name:'Buka'}).click();
 assert.equal(await page.evaluate(()=>STATE.activeBillId),saved);
 assert.equal(await page.evaluate(()=>STATE.activeBills.length),2);
 await page.setViewportSize({width:1024,height:768});
 await page.getByRole('button',{name:'Pilih Aren Latte',exact:true}).click();
 await page.screenshot({path:path.join(output,'modifier-tablet.png'),fullPage:true});
 const layout=await page.locator('#modifierForm .modifier-grid').evaluate(el=>getComputedStyle(el).display);
 assert.equal(layout,'grid');
 await page.locator('#modifierModal button[type="submit"]').focus();
 await page.keyboard.press('Tab');
 assert.equal(await page.getByRole('button',{name:'Tutup detail produk'}).evaluate(el=>el===document.activeElement),true);
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('#modifierModal').isVisible(),false);
 assert.deepEqual(errors,[]);
 await browser.close();
 console.log('PASS: modifiers, edits, safe notes, save/reopen bills, kitchen revisions without duplicates, unpaid accounting isolation, discounted payment, insufficient cash, receipt, filters, preserved drafts. Screenshots: '+output);
})().catch(e=>{console.error(e);process.exit(1)});
